#! /bin/sh

#bspc monitor -d I II III IV V VI VII VIII IX X

bspc monitor HDMI-0 -s ^1
bspc monitor ^1 -d 1 2
bspc monitor ^2 -d 3 4

bspc config pointer_follows_monitor true
bspc config focus_follows_mouse true
bspc config auto_cancel true

bspc config top_padding 25
bspc config border_width        3
bspc config window_gap          25
bspc config split_ratio         0.52
bspc config borderless_monocle  true
bspc config gapless_monocle     true

#bspc rule -a Gimp desktop=^8 follow=on floating=on
bspc rule -a Gimp follow=on floating=on
bspc rule -a Steam follow=on floating=on
bspc rule -a hl2_linux fullscreen=on
#bspc rule -a Chromium desktop=^1
bspc rule -a mplayer floating=on
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
